import type { Role } from "@/types/api.types";

/**
 * Standard audit actions generated by backend services
 * (UserRoleManagement, AIModelManagement, PatientAccountService).
 */
export type AuditAction =
  // User Role Management
  | "CREATE_ACCOUNT"
  | "UPDATE_ACCOUNT"
  | "DEACTIVATE_ACCOUNT"
  | "REACTIVATE_ACCOUNT"
  | "ACCOUNT_LOCK"
  | "ACCOUNT_UNLOCK"
  | "ADMIN_RESET_PASSWORD"
  | "SELF_RESET_PASSWORD"
  // AI Model Management
  | "REGISTER_AI_MODEL"
  | "UPDATE_AI_MODEL"
  | "ACTIVATE_AI_MODEL"
  // Patient / Nurse operations
  | "NURSE_CREATE_PATIENT_ACCOUNT"
  | "NURSE_UPDATE_PATIENT_ACCOUNT"
  | "NURSE_RESET_PATIENT_PASSWORD"
  | string;

/**
 * Filter categories for audit log grouping.
 */
export type AuditCategory = "ALL" | "ACCOUNT" | "AI_MODEL" | "NURSE_PATIENT";

/**
 * Single audit log record matching backend contract ApiResponse<PagedResult<AuditLogResponse>>.
 */
export interface AuditLogEntry {
  logId: string;
  actorId: string;
  actorName: string;
  actorRole: Role | string;
  action: AuditAction;
  detail: string | null;
  performedAt: string; // ISO UTC DateTime
}

/**
 * Parameters for querying paged audit logs.
 */
export interface AuditLogsQueryParams {
  page?: number;
  pageSize?: number;
  search?: string;
  action?: string;
  fromDate?: string;
  toDate?: string;
}

/**
 * Category filter definition.
 */
export interface AuditLogCategoryOption {
  value: AuditCategory;
  label: string;
}

export const AUDIT_CATEGORIES: readonly AuditLogCategoryOption[] = [
  { value: "ALL", label: "Tất cả danh mục" },
  { value: "ACCOUNT", label: "Quản trị tài khoản" },
  { value: "AI_MODEL", label: "Mô hình AI" },
  { value: "NURSE_PATIENT", label: "Điều dưỡng & Bệnh nhân" },
] as const;
